aws/porting-assistant-dotnet-datastore

.gitignore
RecommendationValidator/RecommendationValidator/Program.cs
RecommendationValidator/RecommendationValidator/RecommendationValidator.csproj
THIRD-PARTY

Modifying JSON validator to simplify it.

Modify JSON validator

---

recommendation/project.all.json
recommendation/system.data.entity.json
recommendation/system.data.sqlclient.json
recommendation/system.runtime.caching.json
recommendation/system.web.http.json
recommendation/system.web.http.odata.json
recommendation/system.web.json
recommendation/system.web.mvc.json

Add recommendation files

---

recommendation/project.all.json
recommendation/system.data.entity.json
recommendation/system.data.sqlclient.json
recommendation/system.runtime.caching.json
recommendation/system.web.http.json
recommendation/system.web.http.odata.json
recommendation/system.web.json
recommendation/system.web.mvc.json

Update ARM64 CPU info in recommendation files

Update ARM CPU info

---

recommendation/project.all.json

Update project file action names

---

recommendation/project.all.json

Remove Startup.cs and Program.cs from file to be archived

---

recommendation/system.data.entity.json
recommendation/system.data.sqlclient.json
recommendation/system.web.http.json
recommendation/system.web.http.odata.json
recommendation/system.web.json
recommendation/system.web.mvc.json

Update using statement validations to ignore occurrences of a namespace inside the code

Update using statement validations 

---

recommendation/project.all.json
recommendation/system.data.entity.json
recommendation/system.data.sqlclient.json
recommendation/system.runtime.caching.json

Closes #24 
Add support for .netstandard2.1

Add support for .netstandard2.1

---

recommendation/microsoft.owin.hosting.json
recommendation/microsoft.owin.json
recommendation/owin.json

This contains 3 rules file for Owin. Owin, Microsoft.Owin and Microsoft.Owin.Hosting.

Owin rules files

---

recommendation/microsoft.owin.json

Must revert last change since we have to wait for new releases before merging in Rules changes.

revert last change to wait for a release

---

recommendation/microsoft.owin.json
recommendation/microsoft.owin.staticfiles.json
recommendation/owin.json

New rules for Owin.StaticFiles for object creation.

New rules for Owin.StaticFiles for object creation.

---

recommendation/microsoft.owin.json

Update owin rule to separate .net core versions

---

recommendation/microsoft.owin.hosting.json
recommendation/microsoft.owin.json
recommendation/microsoft.owin.staticfiles.json
recommendation/owin.json
recommendation/system.data.entity.json
recommendation/system.web.http.json
recommendation/system.web.http.odata.json
recommendation/system.web.json
recommendation/system.web.mvc.json

*Issue #38 
We need to make the action validations more readable by adding spaces where appropriate. The validation process already trims the spaces in the action validations.

Add spaces to action validations and remove duplicates.

---

recommendation/microsoft.owin.hosting.json
recommendation/microsoft.owin.json
recommendation/microsoft.owin.staticfiles.json
recommendation/owin.json
recommendation/system.web.json

*Issue #49 
Currently we check all comments and other actions the same way, we should add some granularity to reduce the amount of errors happening during validation due to comments impact.
This will allows us to receive less false positive errors during action validations.

Add Action validation for comments new comment check.

---

recommendation/system.configuration.json
recommendation/system.web.configuration.json

Remove configuration namespaces when replacing configuration code

---

Templates/classlibrary/appsettings.json
Templates/default.json
Templates/mvc/Program.cs
Templates/mvc/Startup.cs
Templates/mvc/appsettings.json
Templates/webapi/Program.cs
Templates/webapi/Startup.cs
Templates/webapi/appsettings.json
Templates/webclasslibrary/appsettings.json

Add resource files

---

recommendation/owin.json

I noticed that some CheckComments flags were missing from some of the addComment porting actions, I am rectifying these oversights.

add missing checkcomments flags.

---

recommendation/system.web.http.odata.json

Update namespace for EnableQuery attribute in latest version

---

recommendation/microsoft.owin.security.json

*Issue #72 
Add new rules file to support Microsoft.Owin.Security namespace. Covers only IAuthenticationManager class for now.

Add new owin security rules files.

---

.github/dependabot.yml
RecommendationValidator/RecommendationValidator/RecommendationValidator.csproj

Closes #78
* Configure dependabot to submit PR's to update dependencies

Configure dependabot

---

recommendation/microsoft.owin.security.json

Add microsoft.owin.security rules namespace for the IAuthenticationManager class.

security rules

---

Templates/mvc/Startup.cs
Templates/webapi/Startup.cs
recommendation/system.web.json

… kestrel options
*Issue #108 

fix: Added rules for Http handlers, modules and added forwarded headers to kestrel

---

Templates/monolithservice/MonolithService.cs

monolith template

---

Templates/monolithservice/MonolithService.cs

make namespace dynamic

---

Templates/monolithservice/MonolithService.cs

fix final template

---

Templates/monolithservice/MonolithService.cs

Update monolith templates to invoke web api controllers

Add support for invoking web api controllers

---

Templates/default.json

fix: add complied features web forms

---

recommendation/microsoft.owin.json
recommendation/microsoft.owin.security.notifications.json
recommendation/microsoft.owin.security.openidconnect.json
recommendation/owin.json
recommendation/system.data.entity.json
recommendation/system.runtime.caching.json

* Fix some rules related to .NET 6

Rules Files: update .NET 6 rules

---

Templates/mvc/Startup.cs
Templates/webapi/Startup.cs
recommendation/system.web.json

fix: added rules to system web

---

recommendation/system.web.json

fix: add net6 target framework

---

recommendation/system.data.entity.json

docs: fix warning message

---

recommendation/microsoft.owin.hosting.json
recommendation/microsoft.owin.infrastructure.json
recommendation/microsoft.owin.json
recommendation/microsoft.owin.security.datahandler.encoder.json
recommendation/microsoft.owin.security.datahandler.json
recommendation/microsoft.owin.security.dataprotection.json
recommendation/microsoft.owin.security.infrastructure.json
recommendation/microsoft.owin.security.json
recommendation/microsoft.owin.security.notifications.json
recommendation/microsoft.owin.staticfiles.json
recommendation/owin.json
recommendation/system.web.http.json
recommendation/system.web.json
recommendation/system.web.mvc.json

fix: add parameter to the rule

---

recommendation/system.web.json

fix: file sync datastore

---

recommendation/system.linq.dynamic.json

* Add porting rules for the DynamicQuery nuget package

add DynamicQuery rules

---

README.md

add period

---

Templates/monolithservice/MonolithServiceCore.cs

Add a class to forward requests to a core application controller

Add a class to forward requests to a core application controller

---

recommendation/org.bouncycastle.crypto.json
recommendation/org.bouncycastle.security.json

* Add rules for BouncyCastle per external contribution
* Rules were tested successfully using CTA

add rules for BouncyCastle

---

Templates/monolithservice/MonolithServiceCore.cs
Templates/monolithservice/MonolithServiceMvc.cs

Update namespace token values to make sure they are replaced when running actions

Update namespace token values

---

tagconfigs/head.yaml

* Modified head config file to use new comment out converter type that will remove embedded comments

Bug Bash Head Config Fix

---

recommendation/NPOI.Excel.json

*Issue #149 *
We need to add a new rule based on a customer contribution to cover porting from NPOI.Excel to NPOI package.

Add new rule based on customer contribution

---

Templates/default.json

fix: update default.json vb feature detection

---

ClientConfiguration/SupportedVersion.json
RecommendationTools/UnitTests/S3SyncTests.cs

*Description of changes: Add NET versions configuration into data store, to benefit from existing data store pipeline to be trackable and to sync with existing public S3 bucket*
Todo: Need to update our existing pipeline before merge this change.

Supported version for client layout into data store to sync with S3

---

ClientConfiguration/SupportedVersion.json

added dotnet 7.0 support version

---

recommendation/project.all.json

1. Add `CreateNet8FolderHierarchy` action to `project.all.json`.

feat: Create hierarchy folder action for .NET 8

---

recommendation/system.data.entity.json

fix 7.0 version

---

ClientConfiguration/SupportedVersion.json

Update SupportedVersion.json to include .NET 8, in case the sync from github to s3 will override the original file again.

Update SupportedVersion.json to include .NET 8

---

Templates/default.json

Add features to template default.json FeatureGroups so CTA feature detector can detect new features. 

Add features to template default.json FeatureGroups
